  /*
 * AUTOMATICALLY GENERATED BY: gen_fpga_mem.pl.
 * DO NOT EDIT
 */
 module data_mem (
    addr,   //< i
    rd,     //< i
    rd_data,//> o
     wr_data,    //< i
    wr,         //< i
     clk     //< i
 );

    //IOs
    input           clk;

    output reg [7:0]    rd_data;
    input [10:0]    addr;
    input           rd;
     input           wr;
    input [7:0]     wr_data;
    reg [7:0] ram [0:2047]; //2KB RAM
 
    always @(negedge clk) begin
         if (wr) begin
            ram[addr] <= wr_data; // Write operation
        end
         if (rd) begin
            rd_data <= ram[addr];    // Read operation
        end
    end
     initial begin
         ram[0] = 8'h48; 
         ram[1] = 8'h65; 
         ram[2] = 8'h6c; 
         ram[3] = 8'h6c; 
         ram[4] = 8'h6f; 
         ram[5] = 8'h20; 
         ram[6] = 8'h77; 
         ram[7] = 8'h6f; 
         ram[8] = 8'h72; 
         ram[9] = 8'h6c; 
         ram[10] = 8'h64; 
         ram[11] = 8'h0a; 
         ram[12] = 8'h0d; 
         ram[13] = 8'h00; 
         ram[14] = 8'h00; 
         ram[15] = 8'h00; 
         ram[16] = 8'h30; 
         ram[17] = 8'h1e; 
         ram[18] = 8'hff; 
         ram[19] = 8'hff; 
     end
 endmodule
