  /*
 * AUTOMATICALLY GENERATED BY: gen_fpga_mem.pl.
 * DO NOT EDIT
 */
 module inst_mem (
    addr,   //< i
    rd,     //< i
    rd_data,//> o
     clk     //< i
 );

    //IOs
    input           clk;

    output reg [7:0]    rd_data;
    input [10:0]    addr;
    input           rd;
     reg [7:0] ram [0:140];  //ROM space is exactly as much the program needs  
 
    always @(negedge clk) begin
         if (rd) begin
            rd_data <= ram[addr];    // Read operation
        end
    end
     initial begin
         ram[0] = 8'hc0; 
         ram[1] = 8'h04; 
         ram[2] = 8'h70; 
         ram[3] = 8'h07; 
         ram[4] = 8'he0; 
         ram[5] = 8'h04; 
         ram[6] = 8'ha0; 
         ram[7] = 8'he0; 
         ram[8] = 8'h64; 
         ram[9] = 8'hb0; 
         ram[10] = 8'hff; 
         ram[11] = 8'h18; 
         ram[12] = 8'h39; 
         ram[13] = 8'hd8; 
         ram[14] = 8'h19; 
         ram[15] = 8'h5f; 
         ram[16] = 8'h01; 
         ram[17] = 8'hf8; 
         ram[18] = 8'h19; 
         ram[19] = 8'h05; 
         ram[20] = 8'h5f; 
         ram[21] = 8'h00; 
         ram[22] = 8'h05; 
         ram[23] = 8'h03; 
         ram[24] = 8'h18; 
         ram[25] = 8'h22; 
         ram[26] = 8'h05; 
         ram[27] = 8'h18; 
         ram[28] = 8'h7c; 
         ram[29] = 8'h18; 
         ram[30] = 8'h7c; 
         ram[31] = 8'h05; 
         ram[32] = 8'h10; 
         ram[33] = 8'h07; 
         ram[34] = 8'h3f; 
         ram[35] = 8'h1e; 
         ram[36] = 8'hf8; 
         ram[37] = 8'h19; 
         ram[38] = 8'h05; 
         ram[39] = 8'h18; 
         ram[40] = 8'h7c; 
         ram[41] = 8'h18; 
         ram[42] = 8'h7c; 
         ram[43] = 8'haf; 
         ram[44] = 8'h3f; 
         ram[45] = 8'h01; 
         ram[46] = 8'hf8; 
         ram[47] = 8'h66; 
         ram[48] = 8'h05; 
         ram[49] = 8'h18; 
         ram[50] = 8'h7c; 
         ram[51] = 8'h18; 
         ram[52] = 8'h7c; 
         ram[53] = 8'haf; 
         ram[54] = 8'hf8; 
         ram[55] = 8'h66; 
         ram[56] = 8'h01; 
         ram[57] = 8'hd8; 
         ram[58] = 8'h18; 
         ram[59] = 8'hf8; 
         ram[60] = 8'h65; 
         ram[61] = 8'h3f; 
         ram[62] = 8'h01; 
         ram[63] = 8'hf8; 
         ram[64] = 8'h18; 
         ram[65] = 8'h5f; 
         ram[66] = 8'h3a; 
         ram[67] = 8'h05; 
         ram[68] = 8'h04; 
         ram[69] = 8'h10; 
         ram[70] = 8'h4b; 
         ram[71] = 8'h3f; 
         ram[72] = 8'h30; 
         ram[73] = 8'hf8; 
         ram[74] = 8'h18; 
         ram[75] = 8'haf; 
         ram[76] = 8'h06; 
         ram[77] = 8'hc8; 
         ram[78] = 8'h08; 
         ram[79] = 8'h07; 
         ram[80] = 8'hd0; 
         ram[81] = 8'h65; 
         ram[82] = 8'h5a; 
         ram[83] = 8'h01; 
         ram[84] = 8'h05; 
         ram[85] = 8'h03; 
         ram[86] = 8'h10; 
         ram[87] = 8'h50; 
         ram[88] = 8'he8; 
         ram[89] = 8'h65; 
         ram[90] = 8'h3f; 
         ram[91] = 8'h01; 
         ram[92] = 8'h55; 
         ram[93] = 8'h00; 
         ram[94] = 8'h05; 
         ram[95] = 8'h04; 
         ram[96] = 8'h10; 
         ram[97] = 8'h4c; 
         ram[98] = 8'h01; 
         ram[99] = 8'he8; 
         ram[100] = 8'h16; 
         ram[101] = 8'hf0; 
         ram[102] = 8'h17; 
         ram[103] = 8'hc8; 
         ram[104] = 8'h1a; 
         ram[105] = 8'hd0; 
         ram[106] = 8'h1b; 
         ram[107] = 8'h5a; 
         ram[108] = 8'h01; 
         ram[109] = 8'h05; 
         ram[110] = 8'h04; 
         ram[111] = 8'h10; 
         ram[112] = 8'h6b; 
         ram[113] = 8'h55; 
         ram[114] = 8'h01; 
         ram[115] = 8'h05; 
         ram[116] = 8'h04; 
         ram[117] = 8'h10; 
         ram[118] = 8'h69; 
         ram[119] = 8'hc8; 
         ram[120] = 8'h16; 
         ram[121] = 8'hd0; 
         ram[122] = 8'h17; 
         ram[123] = 8'h01; 
         ram[124] = 8'h18; 
         ram[125] = 8'h63; 
         ram[126] = 8'h18; 
         ram[127] = 8'h63; 
         ram[128] = 8'h18; 
         ram[129] = 8'h63; 
         ram[130] = 8'h18; 
         ram[131] = 8'h63; 
         ram[132] = 8'h18; 
         ram[133] = 8'h63; 
         ram[134] = 8'h18; 
         ram[135] = 8'h63; 
         ram[136] = 8'h18; 
         ram[137] = 8'h63; 
         ram[138] = 8'h18; 
         ram[139] = 8'h63; 
         ram[140] = 8'h01; 
     end
 endmodule
