#!/usr/bin/perl
use warnings;
use strict;
use Getopt::Long qw(GetOptions);

#########################NOTE#########################
#this utility is for reading output from assembler and
#generate inst_mem.v/data_mem.v for ice40 FPGA as of
#now it can generate memories upto 512B only, and 
#instances a single SB_RAM40_4K block ram.
######################################################

#######get args#############
my $input_file="code.txt";
my $mem_type="inst";
my $target="xilinx";
GetOptions('input_file=s' => \$input_file,
           'type=s' => \$mem_type,
           'target=s' => \$target
          ) or die "Usage: $0 -input_file FILENAME -type <inst|data> -target <lattice|xilinx>\n";

die "invalid option for -type arg. legal options are:\ninst\ndata\n" if(!($mem_type =~ /(inst|data)/));
###########################

my @vlog_out = "";

push(@vlog_out, << "VLOG_END");
 /*
 * AUTOMATICALLY GENERATED BY: gen_fpga_mem.pl.
 * DO NOT EDIT
 */
 module ${mem_type}_mem (
    addr,   //< i
    rd,     //< i
    rd_data,//> o
VLOG_END
if($mem_type =~ /data/) {
push(@vlog_out, << "VLOG_END");
    wr_data,    //< i
    wr,         //< i
VLOG_END
}
push(@vlog_out, << "VLOG_END");
    clk     //< i
 );

    //IOs
    input           clk;

    output reg [7:0]    rd_data;
    input [10:0]    addr;
    input           rd;
VLOG_END
if($mem_type =~ /data/) {
push(@vlog_out, << "VLOG_END");
    input           wr;
    input [7:0]     wr_data;
    reg [7:0] ram [0:2047]; //2KB RAM
VLOG_END
}else{
my $inst_bytes = `cat $input_file | wc -l`;
my $inst_bytes_m_1 = $inst_bytes - 1;
push(@vlog_out, << "VLOG_END");
    reg [7:0] ram [0:$inst_bytes_m_1];  //ROM space is exactly as much the program needs  
VLOG_END
}

push(@vlog_out, << "VLOG_END");

    always @(negedge clk) begin
VLOG_END
if($mem_type eq "data") {
push(@vlog_out, << "VLOG_END");
        if (wr) begin
            ram[addr] <= wr_data; // Write operation
        end
VLOG_END
}
push(@vlog_out, << "VLOG_END");
        if (rd) begin
            rd_data <= ram[addr];    // Read operation
        end
    end
VLOG_END

open(INPUT_FILE, "<${input_file}") or die "Unable to open file ${input_file}, $!";
push(@vlog_out, << "VLOG_END");
    initial begin
VLOG_END
my $index = 0;
while(<INPUT_FILE>) {
    my $line = $_;
    $line =~ s/\n//g;
    $line =~ s/0x/8'h/g;
push(@vlog_out, << "VLOG_END");
        ram[$index] = $line; 
VLOG_END
    $index++;
}
push(@vlog_out, << "VLOG_END");
    end
 endmodule
VLOG_END
##push(@vlog_out, << "VLOG_END");
##    initial begin
##        \$readmemh("$input_file", ram); // Load initialization data
##    end
## endmodule
##VLOG_END


if($mem_type eq "inst") {
    open(OUTPUT_FILE, ">inst_mem.v") or die "Unable to open file inst_mem.v $!";
    printf OUTPUT_FILE "@vlog_out";
}else{
    open(OUTPUT_FILE, ">data_mem.v") or die "Unable to open file data_mem.v $!";
    printf OUTPUT_FILE "@vlog_out";
}
close(OUTPUT_FILE);
close(INPUT_FILE);
